### ISSUE TITLE
Hello, I'm trying run code on my PC, and I need your help.

### ISSUE THREAD

**Issue by ha2sd** [mingqian000/TrGNN#2]
There is no 'ParsedTaxiData_20160315.csv' in the data folder, so 'recovered_trajectory_df_20160315_20160315.csv' can not be generated, could you please send me 'ParsedTaxiData_20160315.csv', or tell me how to get it. Thank you very much!

**Comment by mingqian000** [comment]
Hi, sorry that raw data are kept confidential and cannot be shared. Dummy data are provided instead (refer to README.md - Dataset description - 2. Trajectories).

**Comment by ha2sd** [comment]
> Hi, sorry that raw data are kept confidential and cannot be shared. Dummy data are provided instead (refer to README.md - Dataset description - 2. Trajectories).

OK. Thanks for your reply!
