### ISSUE TITLE
Hello, I have a question about Traffic Status..

### ISSUE THREAD

**Issue by ha2sd** [mingqian000/TrGNN#3]
I thought of the Traffic Status you mentioned in your paper as assigning the traffic flow according to the weighted adjacency matrix(usage the GraphProp), is it? The weights only consider roads, but not trajectories, right? Looking forward to your reply!

**Comment by mingqian000** [comment]
Hi hi, yes and yes to your two questions. The traffic status of a particular road (i.e. an element in the traffic status tensor) is the weighted sum of the flows on its neighbouring roads, with higher weights assigned to nearer roads and lower weights to farther roads.
